name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "pii-obfuscation" #Must be unique in Heroku
          heroku_email: "deagan.c@gmail.com"
          usedocker: true
          healthcheck: "/healthcheck"
          appdir: "app"